[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-merge-conflict"

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0"
hooks = [{ id = "ruff", args = ["--fix"] }]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.10.3"
hooks = [{ id = "uv-lock" }]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ty-check"
name = "ty check"
entry = "uvx ty@0.0.37 check"
language = "system"
pass_filenames = false
types = ["python"]
