"""BBR's own code lists, as it publishes them.

Generated by scripts/generate_bbr_codes.py from the CSV Klimadatastyrelsen
publishes; edit that script rather than this file. A code BBR answers with
and this does not know is shown as itself rather than guessed at, so a new
edition of the lists degrades into an honest number instead of a wrong word.

The labels are the register's own Danish and are never translated.
"""

from __future__ import annotations

# byg021BygningensAnvendelse - BBR's BygAnvendelse, 105 codes.
BYGNINGENS_ANVENDELSE = {
    '110': 'Stuehus til landbrugsejendom',
    '120': 'Fritliggende enfamiliehus',
    '121': 'Sammenbygget enfamiliehus',
    '122': 'Fritliggende enfamiliehus i tæt-lav bebyggelse',
    '130': '(UDFASES) Række-, kæde-, eller dobbelthus (lodret adskillelse mellem '
           'enhederne).',
    '131': 'Række-, kæde- og klyngehus',
    '132': 'Dobbelthus',
    '140': 'Etagebolig-bygning, flerfamiliehus eller to-familiehus',
    '150': 'Kollegium',
    '160': 'Boligbygning til døgninstitution',
    '185': 'Anneks i tilknytning til helårsbolig.',
    '190': 'Anden bygning til helårsbeboelse',
    '210': '(UDFASES) Bygning til erhvervsmæssig produktion vedrørende landbrug, '
           'gartneri, råstofudvinding o. lign',
    '211': 'Stald til svin',
    '212': 'Stald til kvæg, får mv.',
    '213': 'Stald til fjerkræ',
    '214': 'Minkhal',
    '215': 'Væksthus',
    '216': 'Lade til foder, afgrøder mv.',
    '217': 'Maskinhus,  garage mv.',
    '218': 'Lade til halm, hø mv.',
    '219': 'Anden bygning til landbrug mv.',
    '220': '(UDFASES) Bygning til erhvervsmæssig produktion vedrørende industri, '
           'håndværk m.v. (fabrik, værksted o.lign.)',
    '221': 'Bygning til industri med integreret produktionsapparat',
    '222': 'Bygning til industri uden integreret produktionsapparat',
    '223': 'Værksted',
    '229': 'Anden bygning til produktion',
    '230': '(UDFASES) El-, gas-, vand- eller varmeværk, forbrændingsanstalt m.v.',
    '231': 'Bygning til energiproduktion',
    '232': 'Bygning til energidistribution',
    '233': 'Bygning til vandforsyning',
    '234': 'Bygning til håndtering af affald og spildevand',
    '239': 'Anden bygning til energiproduktion og forsyning',
    '290': '(UDFASES) Anden bygning til landbrug, industri etc.',
    '310': '(UDFASES) Transport- og garageanlæg (fragtmandshal, lufthavnsbygning, '
           'banegårdsbygning, parkeringshus). Garage med plads til et eller to køretøjer '
           'registreres med anvendelseskode 910',
    '311': 'Bygning til jernbane- og busdrift',
    '312': 'Bygning til luftfart',
    '313': 'Bygning til parkering- og transportanlæg',
    '314': 'Bygning til parkering af flere end to køretøjer i tilknytning til boliger',
    '315': 'Havneanlæg',
    '319': 'Andet transportanlæg',
    '320': '(UDFASES) Bygning til kontor, handel, lager, herunder offentlig '
           'administration',
    '321': 'Bygning til kontor',
    '322': 'Bygning til detailhandel',
    '323': 'Bygning til lager',
    '324': 'Butikscenter',
    '325': 'Tankstation',
    '329': 'Anden bygning til kontor, handel og lager',
    '330': '(UDFASES) Bygning til hotel, restaurant, vaskeri, frisør og anden '
           'servicevirksomhed',
    '331': 'Hotel, kro eller konferencecenter med overnatning',
    '332': 'Bed & breakfast mv.',
    '333': 'Restaurant, café og konferencecenter uden overnatning',
    '334': 'Privat servicevirksomhed som frisør, vaskeri, netcafé mv.',
    '339': 'Anden bygning til serviceerhverv',
    '390': '(UDFASES) Anden bygning til transport, handel etc',
    '410': '(UDFASES) Bygning til biograf, teater, erhvervsmæssig udstilling, bibliotek, '
           'museum, kirke o. lign.',
    '411': 'Biograf, teater, koncertsted mv.',
    '412': 'Museum',
    '413': 'Bibliotek',
    '414': 'Kirke eller anden bygning til trosudøvelse for statsanerkendte trossamfund',
    '415': 'Forsamlingshus',
    '416': 'Forlystelsespark',
    '419': 'Anden bygning til kulturelle formål',
    '420': '(UDFASES) Bygning til undervisning og forskning (skole, gymnasium, '
           'forskningslabratorium o.lign.).',
    '421': 'Grundskole',
    '422': 'Universitet',
    '429': 'Anden bygning til undervisning og forskning',
    '430': '(UDFASES) Bygning til hospital, sygehjem, fødeklinik o. lign.',
    '431': 'Hospital og sygehus',
    '432': 'Hospice, behandlingshjem mv.',
    '433': 'Sundhedscenter, lægehus, fødeklinik mv.',
    '439': 'Anden bygning til sundhedsformål',
    '440': '(UDFASES) Bygning til daginstitution',
    '441': 'Daginstitution',
    '442': 'Servicefunktion på døgninstitution',
    '443': 'Kaserne',
    '444': 'Fængsel, arresthus mv.',
    '449': 'Anden bygning til institutionsformål',
    '451': 'Beskyttelsesrum',
    '490': '(UDFASES) Bygning til anden institution, herunder kaserne, fængsel o. lign.',
    '510': 'Sommerhus',
    '520': '(UDFASES) Bygning til feriekoloni, vandrehjem o.lign. bortset fra sommerhus',
    '521': 'Feriecenter, center til campingplads mv.',
    '522': 'Bygning med ferielejligheder til erhvervsmæssig udlejning',
    '523': 'Bygning med ferielejligheder til eget brug',
    '529': 'Anden bygning til ferieformål',
    '530': '(UDFASES) Bygning i forbindelse med idrætsudøvelse (klubhus, idrætshal, '
           'svømmehal o. lign.)',
    '531': 'Klubhus i forbindelse med fritid og idræt',
    '532': 'Svømmehal',
    '533': 'Idrætshal',
    '534': 'Tribune i forbindelse med stadion',
    '535': 'Bygning til træning og opstaldning af heste',
    '539': 'Anden bygning til idrætformål',
    '540': 'Kolonihavehus',
    '585': 'Anneks i tilknytning til fritids- og sommerhus',
    '590': 'Anden bygning til fritidsformål',
    '910': 'Garage',
    '920': 'Carport',
    '930': 'Udhus',
    '940': 'Drivhus',
    '950': 'Fritliggende overdækning',
    '960': 'Fritliggende udestue',
    '970': 'Tiloversbleven landbrugsbygning',
    '990': 'Faldefærdig bygning',
    '999': 'Ukendt bygning',
}

# byg032YdervaeggensMateriale - BBR's YdervaeggenesMateriale, 12 codes.
YDERVAEG = {
    '1': 'Mursten',
    '2': 'Letbetonsten',
    '3': 'Fibercement herunder asbest',
    '4': 'Bindingsværk',
    '5': 'Træ',
    '6': 'Betonelementer',
    '8': 'Metal',
    '10': 'Fibercement uden asbest',
    '11': 'Plastmaterialer',
    '12': 'Glas',
    '80': 'Ingen',
    '90': 'Andet materiale',
}

# byg033Tagdaekningsmateriale - BBR's Tagdaekningsmateriale, 13 codes.
TAGDAEKNING = {
    '1': 'Tagpap med lille hældning',
    '2': 'Tagpap med stor hældning',
    '3': 'Fibercement herunder asbest',
    '4': 'Betontagsten',
    '5': 'Tegl',
    '6': 'Metal',
    '7': 'Stråtag',
    '10': 'Fibercement uden asbest',
    '11': 'Plastmaterialer',
    '12': 'Glas',
    '20': 'Levende tage',
    '80': '(UDFASES) Ingen',
    '90': 'Andet materiale',
}

# byg056Varmeinstallation - BBR's Varmeinstallation, 9 codes.
VARMEINSTALLATION = {
    '1': 'Fjernvarme/blokvarme',
    '2': 'Centralvarme med én fyringsenhed',
    '3': 'Ovn til fast og flydende brændsel',
    '5': 'Varmepumpe',
    '6': 'Centralvarme med to fyringsenheder',
    '7': 'Elvarme',
    '8': 'Gasradiator',
    '9': 'Ingen varmeinstallation',
    '99': 'Varmeinstallation er registreret på enheder',
}

# byg058SupplerendeVarme - BBR's BygSupplerendeVarme, 11 codes.
SUPPLERENDE_VARME = {
    '0': 'Ikke oplyst',
    '1': 'Varmepumpe',
    '2': 'Brændeovne og lignende med skorsten',
    '3': 'Biopejse og lignende uden skorsten',
    '4': 'Solvarmeanlæg',
    '5': 'Pejs',
    '6': 'Gasradiator',
    '7': 'Elvarme',
    '10': 'Biogasanlæg',
    '80': 'Andet',
    '90': '(UDFASES) Bygningen har ingen supplerende varme',
}

# enh020EnhedensAnvendelse - BBR's EnhAnvendelse, 101 codes.
ENHEDENS_ANVENDELSE = {
    '110': 'Stuehus til landbrugsejendom',
    '120': 'Fritliggende enfamiliehus',
    '121': 'Sammenbygget enfamiliehus',
    '122': 'Fritliggende enfamiliehus i tæt-lav bebyggelse',
    '130': '(UDFASES) Række-, kæde- eller dobbelthus (lodret adskillelse mellem '
           'enhederne).',
    '131': 'Række-, kæde- og klyngehus',
    '132': 'Dobbelthus',
    '140': 'Bolig i etageejendom, flerfamiliehus eller to-familiehus',
    '150': 'Kollegiebolig',
    '160': 'Bolig i døgninstitution',
    '185': 'Anneks i tilknytning til helårsbolig',
    '190': 'Anden enhed til helårsbeboelse',
    '210': '(UDFASES) Erhvervsmæssig produktion vedrørende landbrug, skovbrug, gartneri, '
           'råstofudvinding og lign.',
    '211': 'Stald til svin',
    '212': 'Stald til kvæg, får mv.',
    '213': 'Stald til fjerkræ',
    '214': 'Minkhal',
    '215': 'Væksthus',
    '216': 'Lade til foder, afgrøder mv.',
    '217': 'Maskinhus,  garage mv.',
    '218': 'Lade til halm, hø mv.',
    '219': 'Anden enhed til landbrug mv.',
    '220': '(UDFASES) Erhvervsmæssig produktion vedrørende industri, håndværk m.v. '
           '(fabrik, værksted o. lign.)',
    '221': 'Enhed til industri med integreret produktionsapparat',
    '222': 'Enhed til industri uden integreret produktionsapparat',
    '223': 'Værksted',
    '229': 'Anden enhed til produktion',
    '230': '(UDFASES) El-, gas-, vand- eller varmeværk, forbrændingsanstalt o. lign.',
    '231': 'Enhed til energiproduktion',
    '232': 'Enhed til energidistribution',
    '233': 'Enhed til vandforsyning',
    '234': 'Enhed til håndtering af affald og spildevand',
    '239': 'Anden enhed til energiproduktion og forsyning',
    '290': '(UDFASES) Anden enhed til produktion og lager i forbindelse med landbrug, '
           'industri o. lign.',
    '310': '(UDFASES) Transport- og garageanlæg (fragtmandshal, '
           'lufthavnsbygning,banegårdsbygning o. lign.)',
    '311': 'Enhed til jernbane- og busdrift',
    '312': 'Enhed til luftfart',
    '313': 'Enhed til parkerings- og transportanlæg',
    '314': 'Enhed til parkering af flere end to køretøjer i tilknytning til boliger',
    '315': 'Havneanlæg',
    '319': 'Andet transportanlæg',
    '320': '(UDFASES) Engroshandel og lager.',
    '321': 'Enhed til kontor',
    '322': 'Enhed til detailhandel',
    '323': 'Enhed til lager',
    '324': 'Butikscenter',
    '325': 'Tankstation',
    '329': 'Anden enhed til kontor, handel og lager',
    '330': '(UDFASES) Detailhandel m.v.',
    '331': 'Hotel, kro eller konferencecenter med overnatning',
    '332': 'Bed & breakfast mv.',
    '333': 'Restaurant, café og konferencecenter uden overnatning',
    '334': 'Privat servicevirksomhed som frisør, vaskeri, netcafé mv.',
    '339': 'Anden enhed til serviceerhverv',
    '340': '(UDFASES) Pengeinstitut, forsikringsvirksomhed m.v.',
    '350': '(UDFASES) Kontor og liberale erhverv bortset fra offentlig administration '
           '(kontorer for advokater, rådgivende ingeniører, klinikker o.lign.)',
    '360': '(UDFASES) Offentlig administration.',
    '370': '(UDFASES) Hotel, restauration, vaskeri, frisør og anden servicevirksomhed.',
    '390': '(UDFASES) Anden enhed til handel, transport etc.',
    '410': '(UDFASES) Biograf, teater, erhvervsmæssig udstilling m.v.',
    '411': 'Biograf, teater, koncertsted mv.',
    '412': 'Museum',
    '413': 'Bibliotek',
    '414': 'Kirke eller anden enhed til trosudøvelse for statsanerkendte trossamfund',
    '415': 'Forsamlingshus',
    '416': 'Forlystelsespark',
    '419': 'Anden enhed til kulturelle formål',
    '420': '(UDFASES) Bibliotek, museum, kirke o. lign.',
    '421': 'Grundskole',
    '422': 'Universitet',
    '429': 'Anden enhed til undervisning og forskning',
    '430': '(UDFASES) Undervisning og forskning (skole, gymnasium, '
           'forskningslaboratorium).',
    '431': 'Hospital og sygehus',
    '432': 'Hospice, behandlingshjem mv.',
    '433': 'Sundhedscenter, lægehus, fødeklinik mv.',
    '439': 'Anden enhed til sundhedsformål',
    '440': '(UDFASES) Hospital, fødeklinik o. lign.',
    '441': 'Daginstitution',
    '442': 'Servicefunktion på døgninstitution',
    '443': 'Kaserne',
    '444': 'Fængsel, arresthus mv.',
    '449': 'Anden enhed til institutionsformål',
    '450': '(UDFASES) Daginstitution.',
    '451': 'Enhed til beskyttelsesrum',
    '490': '(UDFASES) Anden institution, herunder kaserne, fængsel m.v.',
    '510': 'Sommerhus.',
    '520': '(UDFASES) Enhed til feriekoloni, vandrehjem o.lign. bortset fra sommerhus',
    '521': 'Feriecenter, center til campingplads mv.',
    '522': 'Ferielejlighed til erhvervsmæssig udlejning',
    '523': 'Ferielejlighed til eget brug',
    '529': 'Anden enhed til ferieformål',
    '530': '(UDFASES) Enhed i forbindelse med idrætsudøvelse (klubhus, idrætshal, '
           'svømmehal o. lign.).',
    '531': 'Klubhus i forbindelse med fritid- og idræt',
    '532': 'Svømmehal',
    '533': 'Idrætshal',
    '534': 'Tribune i forbindelse med stadion',
    '535': 'Enhed til træning og opstaldning af heste',
    '539': 'Anden enhed til idrætsformål',
    '540': 'Kolonihavehus',
    '585': 'Anneks i tilknytning til fritids- og sommerhus',
    '590': 'Anden enhed til fritidsformål',
}

# enh023Boligtype - BBR's Boligtype, 6 codes.
BOLIGTYPE = {
    '1': 'Egentlig beboelseslejlighed med eget køkken',
    '2': 'Blandet bolig og erhverv med eget køkken',
    '3': 'Enkeltværelse uden eget køkken',
    '4': 'Fællesbolig',
    '5': 'Sommer- eller fritidsbolig',
    'E': 'Andet',
}

# enh032Toiletforhold - BBR's Toiletforhold, 3 codes.
TOILETFORHOLD = {
    'A': 'Vandskyllende toilet uden for enheden',
    'B': 'Intet vandskyllende toilet',
    'T': 'Vandskyllende toilet i enheden',
}

# enh033Badeforhold - BBR's Badeforhold, 3 codes.
BADEFORHOLD = {
    'C': 'Adgang til badeværelse',
    'D': 'Hverken badeværelse eller adgang til badeværelse',
    'V': 'Badeværelse i enheden',
}

# enh034Koekkenforhold - BBR's Koekkenforhold, 4 codes.
KOEKKENFORHOLD = {
    'E': 'Eget køkken med afløb',
    'F': 'Adgang til fælles køkken',
    'G': 'Fast kogeinstallation i værelse eller på gang',
    'H': 'Ingen fast kogeinstallation',
}

# status - BBR's Livscyklus, 23 codes.
LIVSCYKLUS = {
    '1': 'Start',
    '2': 'Projekteret',
    '3': 'Under Opførelse',
    '4': 'Sagsgrund',
    '5': 'Oprettet',
    '6': 'Opført',
    '7': 'Gældende',
    '8': 'Godkendt',
    '9': 'Afsluttet',
    '10': 'Historisk',
    '11': 'Fejlregistreret',
    '12': 'Midlertidig Afsluttet',
    '13': 'Delvis Afsluttet',
    '14': 'Henlagt',
    '15': 'Modtaget',
    '16': 'UnderBehandling',
    '17': 'Fejl',
    '18': 'Udført',
    '19': 'Foreløbig',
    '20': 'BomSagModtaget',
    '21': 'BomSagUnderBehandling',
    '22': 'BomSagFejl',
    '23': 'BomSagUdført',
}

# Which list decodes which field, for the readers in bbr.py.
FOR_FIELD = {
    'byg021BygningensAnvendelse': BYGNINGENS_ANVENDELSE,
    'byg032YdervaeggensMateriale': YDERVAEG,
    'byg033Tagdaekningsmateriale': TAGDAEKNING,
    'byg056Varmeinstallation': VARMEINSTALLATION,
    'byg058SupplerendeVarme': SUPPLERENDE_VARME,
    'enh020EnhedensAnvendelse': ENHEDENS_ANVENDELSE,
    'enh023Boligtype': BOLIGTYPE,
    'enh032Toiletforhold': TOILETFORHOLD,
    'enh033Badeforhold': BADEFORHOLD,
    'enh034Koekkenforhold': KOEKKENFORHOLD,
    'status': LIVSCYKLUS,
}


def label(field: str, code) -> str:
    """The register's word for a code, or the code itself.

    An unknown code is returned unchanged rather than blanked: BBR
    adding a value should show up as a number nobody recognises, not as
    an empty cell that looks like missing data.
    """
    if code in (None, ''):
        return ''
    text = str(code).strip()
    return FOR_FIELD.get(field, {}).get(text, text)
