"""Write src/yaybo/enrich/bbr_codes.py from BBR's own published code lists.

BBR answers in codes. A building's heating is `"1"`, its walls are `"1"`, its
use is `"140"`, and rendering any of that for a person needs the register's own
list of what those mean. The lists are published by Klimadatastyrelsen as one
CSV covering every code list in BBR:

    https://confluence.kds.dk/pages/viewpage.action?pageId=195625667

Generated rather than hand-typed, and the result is committed, so reading a BBR
row costs no request and no dependency. Re-run this when BBR publishes a new
edition of the lists:

    uv run python scripts/generate_bbr_codes.py

The labels are Danish and stay Danish. They are the register's own words for
its own values, which is the same rule the rest of the project follows: the
interface is translated, the data is not.
"""

from __future__ import annotations

import csv
import io
import sys
import textwrap
from pathlib import Path

import requests

CSV_URL = (
    "https://confluence.kds.dk/download/attachments/195625667/BBRKodelister.csv"
    "?version=1&api=v2"
)
ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "yaybo" / "enrich" / "bbr_codes.py"

# The BBR field each list decodes, and the name it goes by in the CSV. Only the
# lists actually read by enrich/bbr.py are carried; BBR publishes forty more.
WANTED = {
    "BYGNINGENS_ANVENDELSE": ("BygAnvendelse", "byg021BygningensAnvendelse"),
    "YDERVAEG": ("YdervaeggenesMateriale", "byg032YdervaeggensMateriale"),
    "TAGDAEKNING": ("Tagdaekningsmateriale", "byg033Tagdaekningsmateriale"),
    "VARMEINSTALLATION": ("Varmeinstallation", "byg056Varmeinstallation"),
    "SUPPLERENDE_VARME": ("BygSupplerendeVarme", "byg058SupplerendeVarme"),
    "ENHEDENS_ANVENDELSE": ("EnhAnvendelse", "enh020EnhedensAnvendelse"),
    "BOLIGTYPE": ("Boligtype", "enh023Boligtype"),
    "TOILETFORHOLD": ("Toiletforhold", "enh032Toiletforhold"),
    "BADEFORHOLD": ("Badeforhold", "enh033Badeforhold"),
    "KOEKKENFORHOLD": ("Koekkenforhold", "enh034Koekkenforhold"),
    "LIVSCYKLUS": ("Livscyklus", "status"),
}


def read(source: str | None) -> list[dict]:
    """The published CSV, from a local path or from Klimadatastyrelsen."""
    if source:
        text = Path(source).read_text(encoding="utf-8")
    else:
        response = requests.get(CSV_URL, timeout=120)
        response.raise_for_status()
        text = response.text
    return list(csv.DictReader(io.StringIO(text)))


def collect(rows: list[dict]) -> dict[str, dict[str, str]]:
    by_list: dict[str, dict[str, str]] = {name: {} for name in WANTED}
    for row in rows:
        listed = (row.get("codelist") or "").strip()
        for constant, (source, _) in WANTED.items():
            if listed == source:
                key = (row.get("key") or "").strip()
                title = (row.get("title") or "").strip()
                if key and title:
                    by_list[constant][key] = title
    missing = [name for name, found in by_list.items() if not found]
    if missing:
        raise SystemExit(f"no codes found for {', '.join(missing)} - has the CSV moved?")
    return by_list


def render(by_list: dict[str, dict[str, str]]) -> str:
    out = [
        '"""BBR\'s own code lists, as it publishes them.',
        "",
        "Generated by scripts/generate_bbr_codes.py from the CSV Klimadatastyrelsen",
        "publishes; edit that script rather than this file. A code BBR answers with",
        "and this does not know is shown as itself rather than guessed at, so a new",
        "edition of the lists degrades into an honest number instead of a wrong word.",
        "",
        "The labels are the register's own Danish and are never translated.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for constant, (source, field) in WANTED.items():
        codes = by_list[constant]
        out.append(f"# {field} - BBR's {source}, {len(codes)} codes.")
        out.append(f"{constant} = {{")
        for key in sorted(codes, key=lambda k: (len(k), k)):
            out.extend(_entry(key, codes[key]))
        out.append("}")
        out.append("")
    out.append("# Which list decodes which field, for the readers in bbr.py.")
    out.append("FOR_FIELD = {")
    for constant, (_, field) in WANTED.items():
        out.append(f"    {field!r}: {constant},")
    out.append("}")
    out.append("")
    out.append("")
    out.append("def label(field: str, code) -> str:")
    out.append('    """The register\'s word for a code, or the code itself.')
    out.append("")
    out.append("    An unknown code is returned unchanged rather than blanked: BBR")
    out.append("    adding a value should show up as a number nobody recognises, not as")
    out.append("    an empty cell that looks like missing data.")
    out.append('    """')
    out.append("    if code in (None, ''):")
    out.append("        return ''")
    out.append("    text = str(code).strip()")
    out.append("    return FOR_FIELD.get(field, {}).get(text, text)")
    return "\n".join(out) + "\n"


def _entry(key: str, title: str) -> list[str]:
    """One dict entry, wrapped to the project's line length.

    Some BBR labels run past ninety characters on their own, so a long one is
    written as adjacent string literals rather than trailing off the line.
    """
    line = f"    {key!r}: {title!r},"
    if len(line) <= 90:
        return [line]
    room = 90 - len(f"    {key!r}: ") - 3
    chunks = textwrap.wrap(title, width=max(room, 20), break_long_words=False) or [title]
    lines = [f"    {key!r}: {chunks[0] + ' '!r}"]
    pad = " " * (len(f"    {key!r}: "))
    for chunk in chunks[1:-1]:
        lines.append(f"{pad}{chunk + ' '!r}")
    lines.append(f"{pad}{chunks[-1]!r},")
    return lines


def main() -> None:
    rows = read(sys.argv[1] if len(sys.argv) > 1 else None)
    OUTPUT.write_text(render(collect(rows)), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
